# Generated by Django 3.2.5 on 2021-07-23 01:49

from django.db import migrations, models
import django.db.models.deletion
import enum


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=50)),
                ('ip', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50)),
                ('processor', models.CharField(max_length=50)),
                ('ram', models.CharField(help_text='Ingrese la cantidad junto a la unidad MB o GB(4 GB)', max_length=50)),
                ('dd', models.CharField(help_text='Ingrese la cantidad junto a la unidad MB o GB(500 GB)', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('m', 'Maintenance'), ('o', 'On loan'), ('a', 'Available'), ('r', 'Reserved')], default='a', help_text='Disponibilidad del Recurso', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('sn', models.DecimalField(decimal_places=0, max_digits=50, verbose_name=enum.unique)),
                ('sa', models.DecimalField(decimal_places=0, max_digits=50, verbose_name=enum.unique)),
                ('notes', models.CharField(max_length=1000)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.category')),
                ('manufacturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.manufacturer')),
                ('net', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.network')),
                ('specs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.specification')),
            ],
        ),
    ]
