# Generated by Django 3.2.5 on 2021-07-23 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_item_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='sa',
            new_name='serial_andes',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='sn',
            new_name='serial_number',
        ),
    ]
