# Generated by Django 3.2.5 on 2021-07-23 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20210723_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='net',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.network'),
        ),
        migrations.AlterField(
            model_name='item',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='specs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.specification'),
        ),
    ]
