# Generated by Django 3.2.5 on 2021-07-24 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_auto_20210723_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='articulo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.item'),
        ),
    ]
