# Generated by Django 3.2.5 on 2021-07-24 00:25

from django.db import migrations, models
import enum


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_network_articulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='serial_number',
            field=models.CharField(max_length=50, verbose_name=enum.unique),
        ),
    ]
