# Generated by Django 3.2.5 on 2021-07-24 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_item_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.item'),
        ),
    ]
