# Generated by Django 3.2.5 on 2021-07-24 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_status_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='ip',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
