# Generated by Django 3.2.5 on 2021-07-26 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_alter_network_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='serial_andes',
            field=models.DecimalField(decimal_places=0, max_digits=50, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='serial_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='articulo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.item'),
        ),
        migrations.AlterField(
            model_name='status',
            name='item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.item'),
        ),
    ]
