# Generated by Django 3.2.5 on 2021-07-30 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_auto_20210726_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
