# Generated by Django 3.2.5 on 2021-07-30 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_category_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='h_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
