# Generated by Django 3.2.5 on 2021-07-31 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_category_h_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='net',
        ),
        migrations.AddField(
            model_name='item',
            name='ip',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='mac',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='reserva',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='serial_andes',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=50, unique=True),
        ),
        migrations.DeleteModel(
            name='Network',
        ),
    ]
