# Generated by Django 3.2.5 on 2021-07-31 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_auto_20210731_0018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='reserva',
            new_name='reserva_ip',
        ),
    ]
