# Generated by Django 3.2.5 on 2021-07-31 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_rename_reserva_item_reserva_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='ip',
            field=models.CharField(blank=True, help_text='172.21.99.54', max_length=15),
        ),
        migrations.AlterField(
            model_name='item',
            name='mac',
            field=models.CharField(blank=True, help_text='4a:c6:b2:40:89:f9', max_length=17),
        ),
    ]
